"""Conservative writers for CIF, POSCAR, and extXYZ."""

from __future__ import annotations

import io
import re
from pathlib import Path
from typing import Any

import numpy as np

from .models import StructureData
from .utils import format_float


def _lattice_parameters(cell: np.ndarray) -> tuple[float, float, float, float, float, float]:
    from pymatgen.core import Lattice

    lattice = Lattice(np.asarray(cell, dtype=float))
    return tuple(float(x) for x in (*lattice.abc, *lattice.angles))


def _p1_site_symmetry_code(image: Any) -> str | None:
    """Encode a periodic image using the CIF P1 ``1_abc`` convention.

    CIF symmetry codes use digits 4/5/6 for translations -1/0/+1.  The
    periodic minimum-image search normally returns values in that range.  If
    a caller supplies a farther image, return ``None`` and retain the exact
    integer image in the DSH audit columns instead of emitting a misleading
    symmetry code.
    """

    try:
        values = [int(round(float(x))) for x in image]
    except (TypeError, ValueError):
        return None
    if len(values) != 3 or any(value < -1 or value > 1 for value in values):
        return None
    return "1_" + "".join(str(5 + value) for value in values)


def cif_text(
    model: StructureData,
    *,
    expand_p1: bool = False,
    include_occupancy: bool = True,
    bond_edges: list[dict[str, Any]] | None = None,
) -> str:
    if model.cell is None:
        raise ValueError("CIF 输出需要晶胞")
    a, b, c, alpha, beta, gamma = _lattice_parameters(np.asarray(model.cell))
    use_source_symmetry = (
        bool(model.metadata.get("symmetry_operations"))
        and not expand_p1
        and not model.metadata.get("expanded_symmetry")
        and not model.metadata.get("symmetry_closed")
    )
    if use_source_symmetry:
        ops = [str(x) for x in model.metadata.get("symmetry_operations", [])]
        space_group = model.metadata.get("declared_space_group") or "P 1"
    else:
        ops = ["x,y,z"]
        # Identity-only output is a P1 representation.  Retaining a source
        # non-P1 label while writing just ``x,y,z`` would make the CIF
        # internally inconsistent and could trigger a second expansion.
        space_group = "P 1"
    block_name = Path(model.source_path or "structure").stem or "structure"
    block_name = "".join(ch if ch.isalnum() or ch in "_-" else "_" for ch in block_name)
    output_labels: list[str] = []
    label_counts: dict[str, int] = {}
    labels_changed = False
    for index, atom in enumerate(model.atoms, start=1):
        original = str(atom.label or f"{atom.element}{index}")
        count = label_counts.get(original, 0) + 1
        label_counts[original] = count
        label = original if count == 1 else f"{original}_{count}"
        while label in output_labels:
            count += 1
            label_counts[original] = count
            label = f"{original}_{count}"
        output_labels.append(label)
        labels_changed |= label != original
    lines = [
        f"data_{block_name}",
        "# generated by dsh-structure-files; source is preserved",
        f"_cell_length_a {format_float(a, 8)}",
        f"_cell_length_b {format_float(b, 8)}",
        f"_cell_length_c {format_float(c, 8)}",
        f"_cell_angle_alpha {format_float(alpha, 6)}",
        f"_cell_angle_beta {format_float(beta, 6)}",
        f"_cell_angle_gamma {format_float(gamma, 6)}",
        f"_symmetry_space_group_name_H-M '{space_group}'",
    ]
    space_group_number = model.metadata.get("space_group_number")
    if space_group == "P 1":
        lines.append("_symmetry_Int_Tables_number 1")
    elif space_group_number not in (None, "", ".", "?"):
        # ASE expects an integer when this optional tag is present.  Avoid
        # writing a literal '?' for an unknown number; omitting the tag is
        # more portable and leaves the declared symbol as the source of truth.
        lines.append(f"_symmetry_Int_Tables_number {int(space_group_number)}")
    lines.extend(["loop_", " _symmetry_equiv_pos_as_xyz"])
    lines.extend(f" '{op}'" for op in ops)
    lines.extend(
        [
            "",
            "loop_",
            " _atom_site_label",
            " _atom_site_type_symbol",
            " _atom_site_fract_x",
            " _atom_site_fract_y",
            " _atom_site_fract_z",
        ]
    )
    if include_occupancy:
        lines.append(" _atom_site_occupancy")
    if any(atom.charge is not None for atom in model.atoms):
        lines.append(" _atom_site_charge")
    if any("disorder_group" in atom.properties for atom in model.atoms):
        lines.append(" _atom_site_disorder_group")
    if any("disorder_assembly" in atom.properties for atom in model.atoms):
        lines.append(" _atom_site_disorder_assembly")
    if any("alt_id" in atom.properties for atom in model.atoms):
        lines.append(" _atom_site_label_alt_id")
    if labels_changed:
        lines.append("# duplicate source labels were deterministically suffixed for CIF output")
    for atom_index, atom in enumerate(model.atoms):
        xyz = (
            atom.coords
            if not model.coords_are_cartesian
            else atom.coords @ np.linalg.inv(np.asarray(model.cell))
        )
        row = [output_labels[atom_index], atom.element, *(format_float(float(v), 8) for v in xyz)]
        if include_occupancy:
            row.append(format_float(atom.occupancy, 5))
        if any(a.charge is not None for a in model.atoms):
            row.append("?" if atom.charge is None else format_float(atom.charge, 4))
        if any("disorder_group" in a.properties for a in model.atoms):
            row.append(str(atom.properties.get("disorder_group", ".")))
        if any("disorder_assembly" in a.properties for a in model.atoms):
            row.append(str(atom.properties.get("disorder_assembly", ".")))
        if any("alt_id" in a.properties for a in model.atoms):
            row.append(str(atom.properties.get("alt_id", ".")))
        lines.append(" ".join(row))
    source_geom_bonds = (
        [] if bond_edges is not None else list(model.metadata.get("geom_bonds") or [])
    )
    if bond_edges is not None or source_geom_bonds:
        # A bond annotation is intentionally separate from the atom loop.  It
        # carries standard geometric-bond fields plus DSH-prefixed provenance
        # fields so an inferred radius contact cannot be mistaken for an
        # experimentally deposited bond order. Existing source ``_geom_bond``
        # rows are retained when no new edge list is supplied.
        inferred = bond_edges is not None
        lines.extend(
            [
                "",
                (
                    "# Bonds below are inferred from periodic covalent radii/coordination "
                    "heuristics."
                    if inferred
                    else "# Existing source _geom_bond rows are preserved; inspect their "
                    "provenance."
                ),
                (
                    "# _geom_bond_type is '?' by policy; inspect the DSH audit fields before use."
                    if inferred
                    else "# DSH fields are retained when present; no new bond assignment was made."
                ),
                "loop_",
                " _geom_bond_atom_site_label_1",
                " _geom_bond_atom_site_label_2",
                " _geom_bond_distance",
                " _geom_bond_site_symmetry_2",
                " _geom_bond_type",
                " _dsh_geom_bond_kind",
                " _dsh_geom_bond_order",
                " _dsh_geom_bond_confidence",
                " _dsh_geom_bond_image_x",
                " _dsh_geom_bond_image_y",
                " _dsh_geom_bond_image_z",
            ]
        )
        normalized_bonds: list[dict[str, Any]] = []
        if inferred:
            for edge in bond_edges or []:
                i = int(edge.get("i", -1))
                j = int(edge.get("j", -1))
                if not (0 <= i < model.n_atoms and 0 <= j < model.n_atoms and i != j):
                    raise ValueError("bond_edges 含越界或自连接索引")
                image = edge.get("image", [0, 0, 0])
                image_values = [int(round(float(x))) for x in image]
                if len(image_values) != 3:
                    raise ValueError("bond_edges 的 image 必须包含 3 个整数")
                normalized_bonds.append(
                    {
                        "label_1": output_labels[i],
                        "label_2": output_labels[j],
                        "distance_A": edge.get("distance"),
                        "site_symmetry_2": _p1_site_symmetry_code(image_values) or "?",
                        "type": "?",
                        "dsh_kind": str(edge.get("kind") or "inferred"),
                        "dsh_order": edge.get("bond_order"),
                        "dsh_confidence": edge.get("confidence"),
                        "dsh_image": image_values,
                    }
                )
        else:
            output_by_source = {
                str(atom.label): label
                for atom, label in zip(model.atoms, output_labels, strict=True)
            }
            for edge in source_geom_bonds:
                left = str(edge.get("label_1") or "?")
                right = str(edge.get("label_2") or "?")
                image = [
                    edge.get("dsh_image_x", 0),
                    edge.get("dsh_image_y", 0),
                    edge.get("dsh_image_z", 0),
                ]
                try:
                    image_values = [int(round(float(x))) for x in image]
                except (TypeError, ValueError):
                    image_values = [0, 0, 0]
                normalized_bonds.append(
                    {
                        "label_1": output_by_source.get(left, left),
                        "label_2": output_by_source.get(right, right),
                        "distance_A": edge.get("distance_A"),
                        "site_symmetry_2": edge.get("site_symmetry_2", "?"),
                        "type": edge.get("type", "?"),
                        "dsh_kind": edge.get("dsh_kind", "source_geom_bond"),
                        "dsh_order": edge.get("dsh_order"),
                        "dsh_confidence": edge.get("dsh_confidence"),
                        "dsh_image": image_values,
                    }
                )
        for edge in normalized_bonds:
            image_values = edge["dsh_image"]
            order = edge.get("dsh_order")
            confidence = edge.get("dsh_confidence")
            row = [
                str(edge["label_1"]),
                str(edge["label_2"]),
                "."
                if edge.get("distance_A") is None
                else format_float(float(edge["distance_A"]), 6),
                str(edge.get("site_symmetry_2") or "?"),
                str(edge.get("type") or "?"),
                str(edge.get("dsh_kind") or "source_geom_bond"),
                "." if order is None else format_float(float(order), 4),
                "." if confidence is None else format_float(float(confidence), 5),
                *(str(value) for value in image_values),
            ]
            lines.append(" ".join(row))
    return "\n".join(lines) + "\n"


def poscar_text(model: StructureData, *, occupancy_policy: str = "reject") -> str:
    if model.cell is None:
        raise ValueError("POSCAR 输出需要晶胞")
    partial = [atom for atom in model.atoms if abs(atom.occupancy - 1.0) > 1e-6]
    if partial and occupancy_policy != "annotate":
        raise ValueError(
            "POSCAR 不支持部分占位；默认拒绝输出。请先选择有证据的有序模型，"
            "或明确传 occupancy_policy='annotate'。"
        )
    species: list[str] = []
    for atom in model.atoms:
        if atom.element not in species:
            species.append(atom.element)
    ordered = [atom for element in species for atom in model.atoms if atom.element == element]
    comment = str(model.metadata.get("comment") or "dsh-structure-files")
    if partial:
        comment += " | WARNING: partial occupancies annotated; not a unique ordered model"
    lines = [comment[:240], "1.0"]
    lines.extend(
        "  " + "  ".join(format_float(float(x), 10) for x in row) for row in np.asarray(model.cell)
    )
    lines.append("  " + "  ".join(species))
    lines.append(
        "  " + "  ".join(str(sum(a.element == element for a in model.atoms)) for element in species)
    )
    lines.append("Direct")
    for atom in ordered:
        xyz = (
            atom.coords
            if not model.coords_are_cartesian
            else atom.coords @ np.linalg.inv(np.asarray(model.cell))
        )
        lines.append("  " + "  ".join(format_float(float(v), 10) for v in xyz))
    return "\n".join(lines) + "\n"


def _ase_atoms(model: StructureData):
    from ase import Atoms

    symbols = [atom.element.split("/")[0] for atom in model.atoms]
    positions = model.coords_cartesian
    kwargs: dict[str, Any] = {"symbols": symbols, "positions": positions}
    if model.cell is not None:
        kwargs["cell"] = np.asarray(model.cell, dtype=float)
        kwargs["pbc"] = model.pbc
    atoms = Atoms(**kwargs)
    atoms.new_array("occupancy", np.asarray([atom.occupancy for atom in model.atoms], dtype=float))
    atoms.new_array("dsh_label", np.asarray([atom.label for atom in model.atoms], dtype="U64"))
    # Carry structure-file provenance and OUTCAR force arrays through extXYZ.
    # ASE only accepts homogeneous numeric/string arrays, so nested or
    # dictionary-valued audit fields remain in the JSON sidecar instead of
    # making the trajectory writer fail.
    used = {"occupancy", "dsh_label"}
    property_keys = sorted({key for atom in model.atoms for key in atom.properties})
    for key in property_keys:
        safe_key = re.sub(r"[^A-Za-z0-9_]", "_", str(key)).strip("_") or "dsh_property"
        if safe_key in used:
            continue
        values = [atom.properties.get(key) for atom in model.atoms]
        try:
            array = np.asarray(values)
            if array.dtype.kind not in "biufcUS" or array.ndim not in {1, 2}:
                continue
            atoms.new_array(safe_key, array)
            used.add(safe_key)
        except (TypeError, ValueError):
            continue
    for key, value in model.metadata.items():
        if isinstance(value, (str, int, float, bool)) or value is None:
            atoms.info[str(key)] = value
    return atoms


def extxyz_text(model: StructureData) -> str:
    import ase.io

    stream = io.StringIO()
    ase.io.write(stream, _ase_atoms(model), format="extxyz")
    return stream.getvalue()


def structure_text(model: StructureData, fmt: str, **kwargs: Any) -> str:
    fmt = fmt.lower()
    if fmt in {"cif", "mcif"}:
        return cif_text(
            model,
            expand_p1=bool(kwargs.get("expand_p1", False)),
            include_occupancy=bool(kwargs.get("include_occupancy", True)),
            bond_edges=kwargs.get("bond_edges"),
        )
    if fmt in {"poscar", "vasp", "contcar"}:
        return poscar_text(model, occupancy_policy=str(kwargs.get("occupancy_policy", "reject")))
    if fmt in {"xyz", "extxyz"}:
        return extxyz_text(model)
    raise ValueError(f"不支持的输出格式: {fmt}")
